name: BiblePlus
options:
  bundleIdPrefix: io.bibleplus
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "6"
    GENERATE_INFOPLIST_FILE: true
    SWIFT_EMIT_LOC_STRINGS: "YES"

schemes:
  BiblePlus:
    build:
      targets:
        BiblePlus: all
    run:
      config: Debug
      storeKitConfiguration: BiblePlus/Configuration.storekit
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  BiblePlus:
    type: application
    platform: iOS
    sources:
      - path: BiblePlus
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
      - path: Resources/Sounds
        buildPhase: resources
      - path: Resources/Backgrounds
        buildPhase: resources
      - path: Resources/Assets.xcassets
        buildPhase: resources
      - path: Resources/Bible
        buildPhase: resources
      - path: Resources/PrivacyInfo.xcprivacy
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.bibleplus.app
        INFOPLIST_FILE: BiblePlus/Info.plist
        CODE_SIGN_ENTITLEMENTS: BiblePlus/BiblePlus.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_NAME: "Bible Plus"
        DEVELOPMENT_TEAM: LRDHWBMA87
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        TARGETED_DEVICE_FAMILY: "1"
    entitlements:
      path: BiblePlus/BiblePlus.entitlements
      properties:
        com.apple.security.application-groups:
          - group.io.bibleplus.shared
    dependencies:
      - target: BiblePlusWidgets
        embed: true

  BiblePlusWidgets:
    type: app-extension
    platform: iOS
    product: com.apple.product-type.app-extension
    sources:
      - path: BiblePlusWidgets
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.bibleplus.app.widgets
        INFOPLIST_FILE: BiblePlusWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: BiblePlusWidgets/BiblePlusWidgets.entitlements
        SKIP_INSTALL: YES
        PRODUCT_NAME: BiblePlusWidgets
        DEVELOPMENT_TEAM: LRDHWBMA87
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
    entitlements:
      path: BiblePlusWidgets/BiblePlusWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.io.bibleplus.shared
