name: BiblePlus
options:
  bundleIdPrefix: com.bibleplus
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: true
    SWIFT_EMIT_LOC_STRINGS: "YES"

targets:
  BiblePlus:
    type: application
    platform: iOS
    sources:
      - path: BiblePlus
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
      - path: Resources/Sounds
        buildPhase: resources
      - path: Resources/Backgrounds
        buildPhase: resources
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/Bible
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bibleplus.app
        INFOPLIST_FILE: BiblePlus/Info.plist
        CODE_SIGN_ENTITLEMENTS: BiblePlus/BiblePlus.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_NAME: "Bible Plus"
    entitlements:
      path: BiblePlus/BiblePlus.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.bibleplus.shared
    dependencies:
      - target: BiblePlusWidgets
        embed: true

  BiblePlusWidgets:
    type: app-extension
    platform: iOS
    product: com.apple.product-type.app-extension
    sources:
      - path: BiblePlusWidgets
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bibleplus.app.widgets
        INFOPLIST_FILE: BiblePlusWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: BiblePlusWidgets/BiblePlusWidgets.entitlements
        SKIP_INSTALL: YES
        PRODUCT_NAME: BiblePlusWidgets
    entitlements:
      path: BiblePlusWidgets/BiblePlusWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.bibleplus.shared
