#!/usr/bin/env python3
"""
Generate Resources/Localizable.xcstrings for Bible Plus.

Why a script: authoring ~60 source strings × ~15 languages by hand in the
Xcode String Catalog JSON shape is error-prone. This builds the file from a
table so future additions are a one-line change.

Usage:
    python3 Scripts/generate_localizable_xcstrings.py

Output:
    Resources/Localizable.xcstrings

When a string has no translation for a given language, the catalog simply
omits that entry and iOS falls back to the English source — users see English
instead of a crash, which is the right behavior.
"""

import json
import os
from collections import OrderedDict

# (key, English source, comment)
STRINGS = [
    # Tab bar
    ("Home", "Home", "Tab bar: feed/dashboard"),
    ("Bible", "Bible", "Tab bar: Bible reader"),
    ("Ask", "Ask", "Tab bar: AI chat"),
    ("Saved", "Saved", "Tab bar: favorites"),
    ("Settings", "Settings", "Tab bar + screen title"),

    # Settings section headers
    ("Profile", "Profile", "Settings section header"),
    ("Notifications", "Notifications", "Settings section header"),
    ("Appearance", "Appearance", "Settings section header"),
    ("Widgets", "Widgets", "Settings section header"),
    ("Subscription", "Subscription", "Settings section header"),
    ("About", "About", "Settings section header"),

    # Settings profile rows
    ("Name", "Name", "Profile row label"),
    ("Faith Level", "Faith Level", "Profile row label"),
    ("Life Seasons", "Life Seasons", "Profile row label"),
    ("Heart Burdens", "Heart Burdens", "Profile row label"),
    ("AI Memory", "AI Memory", "Profile row label"),
    ("Welcome", "Welcome", "Fallback first name"),
    ("Not set", "Not set", "Empty field placeholder"),
    ("Empty", "Empty", "Empty state"),
    ("Digest only", "Digest only", "AI memory state"),
    ("Changes to your profile will refresh your feed.", "Changes to your profile will refresh your feed.", "Profile section footer"),

    # Notifications section
    ("Prayer Times", "Prayer Times", "Notifications row"),
    ("Faith Boosts", "Faith Boosts", "Notifications row"),
    ("Verses & prayers throughout your day", "Verses & prayers throughout your day", "Faith Boosts subtitle"),
    ("Topics", "Topics", "Notification topics row"),
    ("Streak Reminders", "Streak Reminders", "Notifications toggle"),
    ("Plan Reminders", "Plan Reminders", "Notifications toggle"),

    # Appearance section
    ("Language", "Language", "Appearance + picker title"),
    ("Soundscape", "Soundscape", "Appearance row"),
    ("Background", "Background", "Appearance row"),

    # Widgets section
    ("Home Screen Widget", "Home Screen Widget", "Widget row"),
    ("Lock Screen Widget", "Lock Screen Widget", "Widget row"),
    ("Widget Background", "Widget Background", "Widget row"),
    ("Setup Guide", "Setup Guide", "Widget row value"),

    # Subscription
    ("Upgrade to Pro", "Upgrade to Pro", "Paywall CTA"),
    ("Unlock all features & content", "Unlock all features & content", "Paywall subtitle"),
    ("All features unlocked", "All features unlocked", "Pro status label"),
    ("Manage", "Manage", "Open subscription management"),
    ("Restore Purchases", "Restore Purchases", "StoreKit restore"),
    ("PRO", "PRO", "Pro badge"),

    # About
    ("Rate the App", "Rate the App", "About row"),
    ("Privacy Policy", "Privacy Policy", "About row"),
    ("Terms of Service", "Terms of Service", "About row"),
    ("Support", "Support", "About row"),

    # Profile picture sheet
    ("Profile Picture", "Profile Picture", "Dialog title"),
    ("Choose from Library", "Choose from Library", "Photo picker action"),
    ("Remove Photo", "Remove Photo", "Photo picker action"),

    # Common actions
    ("Done", "Done", "Dismiss button"),
    ("Cancel", "Cancel", "Dismiss action"),
    ("Save", "Save", "Commit action"),
    ("OK", "OK", "Dismiss dialog"),
    ("Close", "Close", "Close action"),
    ("Continue", "Continue", "Advance action"),
    ("Back", "Back", "Navigate back"),
    ("Next", "Next", "Navigate forward"),
    ("Skip", "Skip", "Onboarding skip"),
    ("Delete", "Delete", "Destructive action"),
    ("Share", "Share", "Share sheet trigger"),
    ("Copy", "Copy", "Copy to clipboard"),
    ("Edit", "Edit", "Begin editing"),

    # Language picker
    ("System", "System", "Follow-device language label"),
    ("Follow device language", "Follow device language", "System option subtitle"),
    ("Languages", "Languages", "Picker section header"),
    ("Search languages", "Search languages", "Search field placeholder"),

    # Data error
    ("Unable to Load Data", "Unable to Load Data", "Data error title"),
]

# Language-code → {english source string: translation}
#
# Strings omitted here fall back to the English source at runtime — that's the
# iOS default and it's the right behavior for a partially-localized app.
# High-frequency UI strings are filled in for the top 15 languages so a user
# who switches to Spanish/French/Chinese/etc immediately sees a localized
# shell. The rest of the languages and less-visible strings can be filled by
# Xcode's "Automatically Translate" action or a follow-up OpenAI/DeepL pass.
TRANSLATIONS = {
    "es": {
        "Home": "Inicio",
        "Bible": "Biblia",
        "Ask": "Preguntar",
        "Saved": "Guardados",
        "Settings": "Ajustes",
        "Profile": "Perfil",
        "Notifications": "Notificaciones",
        "Appearance": "Apariencia",
        "Widgets": "Widgets",
        "Subscription": "Suscripción",
        "About": "Información",
        "Name": "Nombre",
        "Faith Level": "Nivel de fe",
        "Life Seasons": "Etapas de la vida",
        "Heart Burdens": "Cargas del corazón",
        "AI Memory": "Memoria de la IA",
        "Welcome": "Bienvenido",
        "Not set": "Sin definir",
        "Empty": "Vacío",
        "Digest only": "Solo resumen",
        "Changes to your profile will refresh your feed.": "Los cambios en tu perfil actualizarán tu feed.",
        "Prayer Times": "Horas de oración",
        "Faith Boosts": "Impulsos de fe",
        "Verses & prayers throughout your day": "Versículos y oraciones a lo largo del día",
        "Topics": "Temas",
        "Streak Reminders": "Recordatorios de racha",
        "Plan Reminders": "Recordatorios del plan",
        "Language": "Idioma",
        "Soundscape": "Paisaje sonoro",
        "Background": "Fondo",
        "Home Screen Widget": "Widget de pantalla de inicio",
        "Lock Screen Widget": "Widget de pantalla de bloqueo",
        "Widget Background": "Fondo del widget",
        "Setup Guide": "Guía de configuración",
        "Upgrade to Pro": "Actualiza a Pro",
        "Unlock all features & content": "Desbloquea todas las funciones y el contenido",
        "All features unlocked": "Todas las funciones desbloqueadas",
        "Manage": "Gestionar",
        "Restore Purchases": "Restaurar compras",
        "PRO": "PRO",
        "Rate the App": "Valorar la app",
        "Privacy Policy": "Política de privacidad",
        "Terms of Service": "Términos de servicio",
        "Support": "Soporte",
        "Profile Picture": "Foto de perfil",
        "Choose from Library": "Elegir de la biblioteca",
        "Remove Photo": "Quitar foto",
        "Done": "Hecho",
        "Cancel": "Cancelar",
        "Save": "Guardar",
        "OK": "OK",
        "Close": "Cerrar",
        "Continue": "Continuar",
        "Back": "Atrás",
        "Next": "Siguiente",
        "Skip": "Omitir",
        "Delete": "Eliminar",
        "Share": "Compartir",
        "Copy": "Copiar",
        "Edit": "Editar",
        "System": "Sistema",
        "Follow device language": "Seguir el idioma del dispositivo",
        "Languages": "Idiomas",
        "Search languages": "Buscar idiomas",
        "Unable to Load Data": "No se pudieron cargar los datos",
    },
    "pt-BR": {
        "Home": "Início",
        "Bible": "Bíblia",
        "Ask": "Perguntar",
        "Saved": "Salvos",
        "Settings": "Ajustes",
        "Profile": "Perfil",
        "Notifications": "Notificações",
        "Appearance": "Aparência",
        "Widgets": "Widgets",
        "Subscription": "Assinatura",
        "About": "Sobre",
        "Name": "Nome",
        "Faith Level": "Nível de fé",
        "Life Seasons": "Fases da vida",
        "Heart Burdens": "Fardos do coração",
        "AI Memory": "Memória da IA",
        "Welcome": "Bem-vindo",
        "Not set": "Não definido",
        "Empty": "Vazio",
        "Digest only": "Apenas resumo",
        "Changes to your profile will refresh your feed.": "Alterações no perfil atualizarão o feed.",
        "Prayer Times": "Horários de oração",
        "Faith Boosts": "Impulsos de fé",
        "Verses & prayers throughout your day": "Versículos e orações ao longo do dia",
        "Topics": "Tópicos",
        "Streak Reminders": "Lembretes de sequência",
        "Plan Reminders": "Lembretes do plano",
        "Language": "Idioma",
        "Soundscape": "Paisagem sonora",
        "Background": "Plano de fundo",
        "Home Screen Widget": "Widget da tela inicial",
        "Lock Screen Widget": "Widget da tela de bloqueio",
        "Widget Background": "Fundo do widget",
        "Setup Guide": "Guia de configuração",
        "Upgrade to Pro": "Fazer upgrade para Pro",
        "Unlock all features & content": "Desbloqueie todos os recursos e conteúdo",
        "All features unlocked": "Todos os recursos desbloqueados",
        "Manage": "Gerenciar",
        "Restore Purchases": "Restaurar compras",
        "PRO": "PRO",
        "Rate the App": "Avaliar o app",
        "Privacy Policy": "Política de privacidade",
        "Terms of Service": "Termos de serviço",
        "Support": "Suporte",
        "Profile Picture": "Foto do perfil",
        "Choose from Library": "Escolher da biblioteca",
        "Remove Photo": "Remover foto",
        "Done": "Concluído",
        "Cancel": "Cancelar",
        "Save": "Salvar",
        "OK": "OK",
        "Close": "Fechar",
        "Continue": "Continuar",
        "Back": "Voltar",
        "Next": "Próximo",
        "Skip": "Pular",
        "Delete": "Excluir",
        "Share": "Compartilhar",
        "Copy": "Copiar",
        "Edit": "Editar",
        "System": "Sistema",
        "Follow device language": "Seguir o idioma do dispositivo",
        "Languages": "Idiomas",
        "Search languages": "Buscar idiomas",
        "Unable to Load Data": "Não foi possível carregar os dados",
    },
    "pt-PT": {
        "Home": "Início",
        "Bible": "Bíblia",
        "Ask": "Perguntar",
        "Saved": "Guardados",
        "Settings": "Definições",
        "Profile": "Perfil",
        "Notifications": "Notificações",
        "Appearance": "Aparência",
        "Widgets": "Widgets",
        "Subscription": "Subscrição",
        "About": "Sobre",
        "Name": "Nome",
        "Faith Level": "Nível de fé",
        "Life Seasons": "Fases da vida",
        "Heart Burdens": "Fardos do coração",
        "AI Memory": "Memória da IA",
        "Welcome": "Bem-vindo",
        "Not set": "Não definido",
        "Empty": "Vazio",
        "Digest only": "Apenas resumo",
        "Changes to your profile will refresh your feed.": "As alterações ao perfil atualizarão o feed.",
        "Prayer Times": "Horas de oração",
        "Faith Boosts": "Reforços de fé",
        "Verses & prayers throughout your day": "Versículos e orações ao longo do dia",
        "Topics": "Tópicos",
        "Streak Reminders": "Lembretes de sequência",
        "Plan Reminders": "Lembretes do plano",
        "Language": "Idioma",
        "Soundscape": "Paisagem sonora",
        "Background": "Fundo",
        "Home Screen Widget": "Widget do ecrã principal",
        "Lock Screen Widget": "Widget do ecrã de bloqueio",
        "Widget Background": "Fundo do widget",
        "Setup Guide": "Guia de configuração",
        "Upgrade to Pro": "Atualizar para Pro",
        "Unlock all features & content": "Desbloqueie todas as funcionalidades e conteúdos",
        "All features unlocked": "Todas as funcionalidades desbloqueadas",
        "Manage": "Gerir",
        "Restore Purchases": "Restaurar compras",
        "PRO": "PRO",
        "Rate the App": "Avaliar a app",
        "Privacy Policy": "Política de privacidade",
        "Terms of Service": "Termos de serviço",
        "Support": "Apoio",
        "Profile Picture": "Fotografia de perfil",
        "Choose from Library": "Escolher da biblioteca",
        "Remove Photo": "Remover fotografia",
        "Done": "Concluído",
        "Cancel": "Cancelar",
        "Save": "Guardar",
        "OK": "OK",
        "Close": "Fechar",
        "Continue": "Continuar",
        "Back": "Voltar",
        "Next": "Seguinte",
        "Skip": "Saltar",
        "Delete": "Eliminar",
        "Share": "Partilhar",
        "Copy": "Copiar",
        "Edit": "Editar",
        "System": "Sistema",
        "Follow device language": "Seguir o idioma do dispositivo",
        "Languages": "Idiomas",
        "Search languages": "Pesquisar idiomas",
        "Unable to Load Data": "Não foi possível carregar os dados",
    },
    "fr": {
        "Home": "Accueil",
        "Bible": "Bible",
        "Ask": "Demander",
        "Saved": "Enregistrés",
        "Settings": "Réglages",
        "Profile": "Profil",
        "Notifications": "Notifications",
        "Appearance": "Apparence",
        "Widgets": "Widgets",
        "Subscription": "Abonnement",
        "About": "À propos",
        "Name": "Nom",
        "Faith Level": "Niveau de foi",
        "Life Seasons": "Saisons de la vie",
        "Heart Burdens": "Fardeaux du cœur",
        "AI Memory": "Mémoire de l'IA",
        "Welcome": "Bienvenue",
        "Not set": "Non défini",
        "Empty": "Vide",
        "Digest only": "Résumé seulement",
        "Changes to your profile will refresh your feed.": "Les modifications du profil actualiseront votre fil.",
        "Prayer Times": "Heures de prière",
        "Faith Boosts": "Coups de pouce spirituels",
        "Verses & prayers throughout your day": "Versets et prières tout au long de la journée",
        "Topics": "Thèmes",
        "Streak Reminders": "Rappels de série",
        "Plan Reminders": "Rappels de plan",
        "Language": "Langue",
        "Soundscape": "Ambiance sonore",
        "Background": "Arrière-plan",
        "Home Screen Widget": "Widget d'écran d'accueil",
        "Lock Screen Widget": "Widget d'écran verrouillé",
        "Widget Background": "Arrière-plan du widget",
        "Setup Guide": "Guide de configuration",
        "Upgrade to Pro": "Passer à Pro",
        "Unlock all features & content": "Débloquez toutes les fonctionnalités et le contenu",
        "All features unlocked": "Toutes les fonctionnalités débloquées",
        "Manage": "Gérer",
        "Restore Purchases": "Restaurer les achats",
        "PRO": "PRO",
        "Rate the App": "Noter l'app",
        "Privacy Policy": "Politique de confidentialité",
        "Terms of Service": "Conditions d'utilisation",
        "Support": "Assistance",
        "Profile Picture": "Photo de profil",
        "Choose from Library": "Choisir depuis la bibliothèque",
        "Remove Photo": "Supprimer la photo",
        "Done": "OK",
        "Cancel": "Annuler",
        "Save": "Enregistrer",
        "OK": "OK",
        "Close": "Fermer",
        "Continue": "Continuer",
        "Back": "Retour",
        "Next": "Suivant",
        "Skip": "Passer",
        "Delete": "Supprimer",
        "Share": "Partager",
        "Copy": "Copier",
        "Edit": "Modifier",
        "System": "Système",
        "Follow device language": "Suivre la langue de l'appareil",
        "Languages": "Langues",
        "Search languages": "Rechercher une langue",
        "Unable to Load Data": "Impossible de charger les données",
    },
    "de": {
        "Home": "Start",
        "Bible": "Bibel",
        "Ask": "Fragen",
        "Saved": "Gespeichert",
        "Settings": "Einstellungen",
        "Profile": "Profil",
        "Notifications": "Mitteilungen",
        "Appearance": "Darstellung",
        "Widgets": "Widgets",
        "Subscription": "Abo",
        "About": "Info",
        "Name": "Name",
        "Faith Level": "Glaubensstufe",
        "Life Seasons": "Lebensphasen",
        "Heart Burdens": "Herzenslasten",
        "AI Memory": "KI-Erinnerung",
        "Welcome": "Willkommen",
        "Not set": "Nicht festgelegt",
        "Empty": "Leer",
        "Digest only": "Nur Zusammenfassung",
        "Changes to your profile will refresh your feed.": "Profiländerungen aktualisieren deinen Feed.",
        "Prayer Times": "Gebetszeiten",
        "Faith Boosts": "Glaubensimpulse",
        "Verses & prayers throughout your day": "Verse und Gebete über den Tag verteilt",
        "Topics": "Themen",
        "Streak Reminders": "Serien-Erinnerungen",
        "Plan Reminders": "Plan-Erinnerungen",
        "Language": "Sprache",
        "Soundscape": "Klanglandschaft",
        "Background": "Hintergrund",
        "Home Screen Widget": "Home-Bildschirm-Widget",
        "Lock Screen Widget": "Sperrbildschirm-Widget",
        "Widget Background": "Widget-Hintergrund",
        "Setup Guide": "Einrichtungsleitfaden",
        "Upgrade to Pro": "Auf Pro upgraden",
        "Unlock all features & content": "Alle Funktionen und Inhalte freischalten",
        "All features unlocked": "Alle Funktionen freigeschaltet",
        "Manage": "Verwalten",
        "Restore Purchases": "Käufe wiederherstellen",
        "PRO": "PRO",
        "Rate the App": "App bewerten",
        "Privacy Policy": "Datenschutz",
        "Terms of Service": "Nutzungsbedingungen",
        "Support": "Support",
        "Profile Picture": "Profilbild",
        "Choose from Library": "Aus Mediathek wählen",
        "Remove Photo": "Foto entfernen",
        "Done": "Fertig",
        "Cancel": "Abbrechen",
        "Save": "Speichern",
        "OK": "OK",
        "Close": "Schließen",
        "Continue": "Weiter",
        "Back": "Zurück",
        "Next": "Weiter",
        "Skip": "Überspringen",
        "Delete": "Löschen",
        "Share": "Teilen",
        "Copy": "Kopieren",
        "Edit": "Bearbeiten",
        "System": "System",
        "Follow device language": "Gerätesprache verwenden",
        "Languages": "Sprachen",
        "Search languages": "Sprachen suchen",
        "Unable to Load Data": "Daten konnten nicht geladen werden",
    },
    "it": {
        "Home": "Home",
        "Bible": "Bibbia",
        "Ask": "Chiedi",
        "Saved": "Salvati",
        "Settings": "Impostazioni",
        "Profile": "Profilo",
        "Notifications": "Notifiche",
        "Appearance": "Aspetto",
        "Widgets": "Widget",
        "Subscription": "Abbonamento",
        "About": "Informazioni",
        "Name": "Nome",
        "Faith Level": "Livello di fede",
        "Life Seasons": "Stagioni della vita",
        "Heart Burdens": "Pesi del cuore",
        "AI Memory": "Memoria dell'IA",
        "Welcome": "Benvenuto",
        "Not set": "Non impostato",
        "Empty": "Vuoto",
        "Digest only": "Solo riassunto",
        "Changes to your profile will refresh your feed.": "Le modifiche al profilo aggiorneranno il tuo feed.",
        "Prayer Times": "Orari di preghiera",
        "Faith Boosts": "Spinte di fede",
        "Verses & prayers throughout your day": "Versetti e preghiere durante la giornata",
        "Topics": "Argomenti",
        "Streak Reminders": "Promemoria della serie",
        "Plan Reminders": "Promemoria del piano",
        "Language": "Lingua",
        "Soundscape": "Paesaggio sonoro",
        "Background": "Sfondo",
        "Home Screen Widget": "Widget schermata Home",
        "Lock Screen Widget": "Widget schermata di blocco",
        "Widget Background": "Sfondo del widget",
        "Setup Guide": "Guida alla configurazione",
        "Upgrade to Pro": "Passa a Pro",
        "Unlock all features & content": "Sblocca tutte le funzionalità e i contenuti",
        "All features unlocked": "Tutte le funzionalità sbloccate",
        "Manage": "Gestisci",
        "Restore Purchases": "Ripristina acquisti",
        "PRO": "PRO",
        "Rate the App": "Valuta l'app",
        "Privacy Policy": "Informativa sulla privacy",
        "Terms of Service": "Termini di servizio",
        "Support": "Supporto",
        "Profile Picture": "Foto profilo",
        "Choose from Library": "Scegli dalla libreria",
        "Remove Photo": "Rimuovi foto",
        "Done": "Fine",
        "Cancel": "Annulla",
        "Save": "Salva",
        "OK": "OK",
        "Close": "Chiudi",
        "Continue": "Continua",
        "Back": "Indietro",
        "Next": "Avanti",
        "Skip": "Salta",
        "Delete": "Elimina",
        "Share": "Condividi",
        "Copy": "Copia",
        "Edit": "Modifica",
        "System": "Sistema",
        "Follow device language": "Segui la lingua del dispositivo",
        "Languages": "Lingue",
        "Search languages": "Cerca lingue",
        "Unable to Load Data": "Impossibile caricare i dati",
    },
    "nl": {
        "Home": "Start",
        "Bible": "Bijbel",
        "Ask": "Vragen",
        "Saved": "Bewaard",
        "Settings": "Instellingen",
        "Profile": "Profiel",
        "Notifications": "Meldingen",
        "Appearance": "Weergave",
        "Widgets": "Widgets",
        "Subscription": "Abonnement",
        "About": "Over",
        "Name": "Naam",
        "Faith Level": "Geloofsniveau",
        "Life Seasons": "Levensfases",
        "Heart Burdens": "Zorgen van het hart",
        "AI Memory": "AI-geheugen",
        "Welcome": "Welkom",
        "Not set": "Niet ingesteld",
        "Empty": "Leeg",
        "Digest only": "Alleen samenvatting",
        "Changes to your profile will refresh your feed.": "Wijzigingen in je profiel vernieuwen je feed.",
        "Prayer Times": "Gebedstijden",
        "Faith Boosts": "Geloofsimpulsen",
        "Verses & prayers throughout your day": "Verzen en gebeden door de dag heen",
        "Topics": "Onderwerpen",
        "Streak Reminders": "Reeks-herinneringen",
        "Plan Reminders": "Plan-herinneringen",
        "Language": "Taal",
        "Soundscape": "Soundscape",
        "Background": "Achtergrond",
        "Home Screen Widget": "Beginscherm-widget",
        "Lock Screen Widget": "Toegangsscherm-widget",
        "Widget Background": "Widget-achtergrond",
        "Setup Guide": "Installatiegids",
        "Upgrade to Pro": "Upgrade naar Pro",
        "Unlock all features & content": "Ontgrendel alle functies en inhoud",
        "All features unlocked": "Alle functies ontgrendeld",
        "Manage": "Beheren",
        "Restore Purchases": "Aankopen herstellen",
        "PRO": "PRO",
        "Rate the App": "Beoordeel de app",
        "Privacy Policy": "Privacybeleid",
        "Terms of Service": "Servicevoorwaarden",
        "Support": "Ondersteuning",
        "Profile Picture": "Profielfoto",
        "Choose from Library": "Uit bibliotheek kiezen",
        "Remove Photo": "Foto verwijderen",
        "Done": "Gereed",
        "Cancel": "Annuleer",
        "Save": "Bewaar",
        "OK": "OK",
        "Close": "Sluit",
        "Continue": "Doorgaan",
        "Back": "Terug",
        "Next": "Volgende",
        "Skip": "Overslaan",
        "Delete": "Verwijder",
        "Share": "Delen",
        "Copy": "Kopieer",
        "Edit": "Bewerk",
        "System": "Systeem",
        "Follow device language": "Volg taal van apparaat",
        "Languages": "Talen",
        "Search languages": "Talen zoeken",
        "Unable to Load Data": "Kan gegevens niet laden",
    },
    "zh-Hans": {
        "Home": "首页",
        "Bible": "圣经",
        "Ask": "询问",
        "Saved": "已保存",
        "Settings": "设置",
        "Profile": "个人资料",
        "Notifications": "通知",
        "Appearance": "外观",
        "Widgets": "小组件",
        "Subscription": "订阅",
        "About": "关于",
        "Name": "名字",
        "Faith Level": "信仰阶段",
        "Life Seasons": "人生阶段",
        "Heart Burdens": "心中重担",
        "AI Memory": "AI 记忆",
        "Welcome": "欢迎",
        "Not set": "未设置",
        "Empty": "空",
        "Digest only": "仅摘要",
        "Changes to your profile will refresh your feed.": "修改个人资料将刷新你的动态。",
        "Prayer Times": "祷告时间",
        "Faith Boosts": "信仰激励",
        "Verses & prayers throughout your day": "全天中的经文与祷告",
        "Topics": "主题",
        "Streak Reminders": "连续提醒",
        "Plan Reminders": "计划提醒",
        "Language": "语言",
        "Soundscape": "环境音",
        "Background": "背景",
        "Home Screen Widget": "主屏幕小组件",
        "Lock Screen Widget": "锁屏小组件",
        "Widget Background": "小组件背景",
        "Setup Guide": "设置指南",
        "Upgrade to Pro": "升级到 Pro",
        "Unlock all features & content": "解锁全部功能与内容",
        "All features unlocked": "全部功能已解锁",
        "Manage": "管理",
        "Restore Purchases": "恢复购买",
        "PRO": "PRO",
        "Rate the App": "为 App 评分",
        "Privacy Policy": "隐私政策",
        "Terms of Service": "服务条款",
        "Support": "支持",
        "Profile Picture": "头像",
        "Choose from Library": "从图库选择",
        "Remove Photo": "移除照片",
        "Done": "完成",
        "Cancel": "取消",
        "Save": "保存",
        "OK": "好",
        "Close": "关闭",
        "Continue": "继续",
        "Back": "返回",
        "Next": "下一步",
        "Skip": "跳过",
        "Delete": "删除",
        "Share": "分享",
        "Copy": "复制",
        "Edit": "编辑",
        "System": "系统",
        "Follow device language": "跟随设备语言",
        "Languages": "语言",
        "Search languages": "搜索语言",
        "Unable to Load Data": "无法加载数据",
    },
    "zh-Hant": {
        "Home": "首頁",
        "Bible": "聖經",
        "Ask": "詢問",
        "Saved": "已儲存",
        "Settings": "設定",
        "Profile": "個人檔案",
        "Notifications": "通知",
        "Appearance": "外觀",
        "Widgets": "小工具",
        "Subscription": "訂閱",
        "About": "關於",
        "Name": "名字",
        "Faith Level": "信仰階段",
        "Life Seasons": "人生階段",
        "Heart Burdens": "心中重擔",
        "AI Memory": "AI 記憶",
        "Welcome": "歡迎",
        "Not set": "未設定",
        "Empty": "空",
        "Digest only": "僅摘要",
        "Changes to your profile will refresh your feed.": "修改個人檔案將更新你的動態。",
        "Prayer Times": "禱告時間",
        "Faith Boosts": "信仰激勵",
        "Verses & prayers throughout your day": "全天的經文與禱告",
        "Topics": "主題",
        "Streak Reminders": "連續提醒",
        "Plan Reminders": "計畫提醒",
        "Language": "語言",
        "Soundscape": "環境音",
        "Background": "背景",
        "Home Screen Widget": "主畫面小工具",
        "Lock Screen Widget": "鎖定畫面小工具",
        "Widget Background": "小工具背景",
        "Setup Guide": "設定指南",
        "Upgrade to Pro": "升級至 Pro",
        "Unlock all features & content": "解鎖所有功能與內容",
        "All features unlocked": "所有功能已解鎖",
        "Manage": "管理",
        "Restore Purchases": "還原購買",
        "PRO": "PRO",
        "Rate the App": "為 App 評分",
        "Privacy Policy": "隱私權政策",
        "Terms of Service": "服務條款",
        "Support": "支援",
        "Profile Picture": "大頭貼",
        "Choose from Library": "從圖庫選擇",
        "Remove Photo": "移除照片",
        "Done": "完成",
        "Cancel": "取消",
        "Save": "儲存",
        "OK": "好",
        "Close": "關閉",
        "Continue": "繼續",
        "Back": "返回",
        "Next": "下一步",
        "Skip": "略過",
        "Delete": "刪除",
        "Share": "分享",
        "Copy": "拷貝",
        "Edit": "編輯",
        "System": "系統",
        "Follow device language": "跟隨裝置語言",
        "Languages": "語言",
        "Search languages": "搜尋語言",
        "Unable to Load Data": "無法載入資料",
    },
    "ja": {
        "Home": "ホーム",
        "Bible": "聖書",
        "Ask": "質問",
        "Saved": "保存済み",
        "Settings": "設定",
        "Profile": "プロフィール",
        "Notifications": "通知",
        "Appearance": "外観",
        "Widgets": "ウィジェット",
        "Subscription": "サブスクリプション",
        "About": "情報",
        "Name": "名前",
        "Faith Level": "信仰の段階",
        "Life Seasons": "人生の季節",
        "Heart Burdens": "心の重荷",
        "AI Memory": "AIの記憶",
        "Welcome": "ようこそ",
        "Not set": "未設定",
        "Empty": "空",
        "Digest only": "要約のみ",
        "Changes to your profile will refresh your feed.": "プロフィールを変更するとフィードが更新されます。",
        "Prayer Times": "祈りの時間",
        "Faith Boosts": "信仰ブースト",
        "Verses & prayers throughout your day": "一日を通しての聖句と祈り",
        "Topics": "トピック",
        "Streak Reminders": "連続日数のリマインダー",
        "Plan Reminders": "プランのリマインダー",
        "Language": "言語",
        "Soundscape": "サウンドスケープ",
        "Background": "背景",
        "Home Screen Widget": "ホーム画面ウィジェット",
        "Lock Screen Widget": "ロック画面ウィジェット",
        "Widget Background": "ウィジェットの背景",
        "Setup Guide": "設定ガイド",
        "Upgrade to Pro": "Proにアップグレード",
        "Unlock all features & content": "すべての機能とコンテンツをアンロック",
        "All features unlocked": "すべての機能がアンロックされています",
        "Manage": "管理",
        "Restore Purchases": "購入情報を復元",
        "PRO": "PRO",
        "Rate the App": "アプリを評価する",
        "Privacy Policy": "プライバシーポリシー",
        "Terms of Service": "利用規約",
        "Support": "サポート",
        "Profile Picture": "プロフィール写真",
        "Choose from Library": "ライブラリから選択",
        "Remove Photo": "写真を削除",
        "Done": "完了",
        "Cancel": "キャンセル",
        "Save": "保存",
        "OK": "OK",
        "Close": "閉じる",
        "Continue": "続ける",
        "Back": "戻る",
        "Next": "次へ",
        "Skip": "スキップ",
        "Delete": "削除",
        "Share": "共有",
        "Copy": "コピー",
        "Edit": "編集",
        "System": "システム",
        "Follow device language": "デバイスの言語に従う",
        "Languages": "言語",
        "Search languages": "言語を検索",
        "Unable to Load Data": "データを読み込めません",
    },
    "ko": {
        "Home": "홈",
        "Bible": "성경",
        "Ask": "질문",
        "Saved": "저장됨",
        "Settings": "설정",
        "Profile": "프로필",
        "Notifications": "알림",
        "Appearance": "모양",
        "Widgets": "위젯",
        "Subscription": "구독",
        "About": "정보",
        "Name": "이름",
        "Faith Level": "신앙 단계",
        "Life Seasons": "인생의 계절",
        "Heart Burdens": "마음의 짐",
        "AI Memory": "AI 기억",
        "Welcome": "환영합니다",
        "Not set": "설정 안 됨",
        "Empty": "비어 있음",
        "Digest only": "요약만",
        "Changes to your profile will refresh your feed.": "프로필을 변경하면 피드가 새로 고쳐집니다.",
        "Prayer Times": "기도 시간",
        "Faith Boosts": "신앙 부스트",
        "Verses & prayers throughout your day": "하루 종일 말씀과 기도",
        "Topics": "주제",
        "Streak Reminders": "연속 기록 알림",
        "Plan Reminders": "플랜 알림",
        "Language": "언어",
        "Soundscape": "사운드스케이프",
        "Background": "배경",
        "Home Screen Widget": "홈 화면 위젯",
        "Lock Screen Widget": "잠금 화면 위젯",
        "Widget Background": "위젯 배경",
        "Setup Guide": "설정 가이드",
        "Upgrade to Pro": "Pro로 업그레이드",
        "Unlock all features & content": "모든 기능과 콘텐츠 잠금 해제",
        "All features unlocked": "모든 기능 잠금 해제됨",
        "Manage": "관리",
        "Restore Purchases": "구매 복원",
        "PRO": "PRO",
        "Rate the App": "앱 평가하기",
        "Privacy Policy": "개인정보 처리방침",
        "Terms of Service": "서비스 약관",
        "Support": "지원",
        "Profile Picture": "프로필 사진",
        "Choose from Library": "라이브러리에서 선택",
        "Remove Photo": "사진 삭제",
        "Done": "완료",
        "Cancel": "취소",
        "Save": "저장",
        "OK": "확인",
        "Close": "닫기",
        "Continue": "계속",
        "Back": "뒤로",
        "Next": "다음",
        "Skip": "건너뛰기",
        "Delete": "삭제",
        "Share": "공유",
        "Copy": "복사",
        "Edit": "편집",
        "System": "시스템",
        "Follow device language": "기기 언어 따르기",
        "Languages": "언어",
        "Search languages": "언어 검색",
        "Unable to Load Data": "데이터를 불러올 수 없습니다",
    },
    "ru": {
        "Home": "Главная",
        "Bible": "Библия",
        "Ask": "Спросить",
        "Saved": "Сохранённое",
        "Settings": "Настройки",
        "Profile": "Профиль",
        "Notifications": "Уведомления",
        "Appearance": "Внешний вид",
        "Widgets": "Виджеты",
        "Subscription": "Подписка",
        "About": "О приложении",
        "Name": "Имя",
        "Faith Level": "Уровень веры",
        "Life Seasons": "Этапы жизни",
        "Heart Burdens": "Бремя сердца",
        "AI Memory": "Память ИИ",
        "Welcome": "Добро пожаловать",
        "Not set": "Не задано",
        "Empty": "Пусто",
        "Digest only": "Только сводка",
        "Changes to your profile will refresh your feed.": "Изменения профиля обновят вашу ленту.",
        "Prayer Times": "Время молитвы",
        "Faith Boosts": "Заряд веры",
        "Verses & prayers throughout your day": "Стихи и молитвы в течение дня",
        "Topics": "Темы",
        "Streak Reminders": "Напоминания о серии",
        "Plan Reminders": "Напоминания о плане",
        "Language": "Язык",
        "Soundscape": "Звуковой фон",
        "Background": "Фон",
        "Home Screen Widget": "Виджет главного экрана",
        "Lock Screen Widget": "Виджет экрана блокировки",
        "Widget Background": "Фон виджета",
        "Setup Guide": "Руководство по настройке",
        "Upgrade to Pro": "Перейти на Pro",
        "Unlock all features & content": "Откройте все функции и контент",
        "All features unlocked": "Все функции открыты",
        "Manage": "Управлять",
        "Restore Purchases": "Восстановить покупки",
        "PRO": "PRO",
        "Rate the App": "Оценить приложение",
        "Privacy Policy": "Политика конфиденциальности",
        "Terms of Service": "Условия использования",
        "Support": "Поддержка",
        "Profile Picture": "Фото профиля",
        "Choose from Library": "Выбрать из медиатеки",
        "Remove Photo": "Удалить фото",
        "Done": "Готово",
        "Cancel": "Отмена",
        "Save": "Сохранить",
        "OK": "OK",
        "Close": "Закрыть",
        "Continue": "Продолжить",
        "Back": "Назад",
        "Next": "Далее",
        "Skip": "Пропустить",
        "Delete": "Удалить",
        "Share": "Поделиться",
        "Copy": "Копировать",
        "Edit": "Редактировать",
        "System": "Системный",
        "Follow device language": "Следовать языку устройства",
        "Languages": "Языки",
        "Search languages": "Поиск языков",
        "Unable to Load Data": "Не удалось загрузить данные",
    },
    "ar": {
        "Home": "الرئيسية",
        "Bible": "الكتاب المقدس",
        "Ask": "اسأل",
        "Saved": "المحفوظ",
        "Settings": "الإعدادات",
        "Profile": "الملف الشخصي",
        "Notifications": "الإشعارات",
        "Appearance": "المظهر",
        "Widgets": "الأدوات",
        "Subscription": "الاشتراك",
        "About": "حول",
        "Name": "الاسم",
        "Faith Level": "مستوى الإيمان",
        "Life Seasons": "مراحل الحياة",
        "Heart Burdens": "أعباء القلب",
        "AI Memory": "ذاكرة الذكاء الاصطناعي",
        "Welcome": "مرحباً",
        "Not set": "غير محدد",
        "Empty": "فارغ",
        "Digest only": "ملخص فقط",
        "Changes to your profile will refresh your feed.": "ستؤدي تغييرات الملف الشخصي إلى تحديث موجزك.",
        "Prayer Times": "أوقات الصلاة",
        "Faith Boosts": "دفعات إيمانية",
        "Verses & prayers throughout your day": "آيات وصلوات طوال يومك",
        "Topics": "المواضيع",
        "Streak Reminders": "تذكيرات التسلسل",
        "Plan Reminders": "تذكيرات الخطة",
        "Language": "اللغة",
        "Soundscape": "المشهد الصوتي",
        "Background": "الخلفية",
        "Home Screen Widget": "أداة الشاشة الرئيسية",
        "Lock Screen Widget": "أداة شاشة القفل",
        "Widget Background": "خلفية الأداة",
        "Setup Guide": "دليل الإعداد",
        "Upgrade to Pro": "الترقية إلى Pro",
        "Unlock all features & content": "افتح جميع الميزات والمحتوى",
        "All features unlocked": "تم فتح جميع الميزات",
        "Manage": "إدارة",
        "Restore Purchases": "استعادة المشتريات",
        "PRO": "PRO",
        "Rate the App": "قيّم التطبيق",
        "Privacy Policy": "سياسة الخصوصية",
        "Terms of Service": "شروط الخدمة",
        "Support": "الدعم",
        "Profile Picture": "صورة الملف الشخصي",
        "Choose from Library": "اختر من المكتبة",
        "Remove Photo": "إزالة الصورة",
        "Done": "تم",
        "Cancel": "إلغاء",
        "Save": "حفظ",
        "OK": "موافق",
        "Close": "إغلاق",
        "Continue": "متابعة",
        "Back": "رجوع",
        "Next": "التالي",
        "Skip": "تخطّ",
        "Delete": "حذف",
        "Share": "مشاركة",
        "Copy": "نسخ",
        "Edit": "تعديل",
        "System": "النظام",
        "Follow device language": "اتّبع لغة الجهاز",
        "Languages": "اللغات",
        "Search languages": "بحث عن لغة",
        "Unable to Load Data": "تعذّر تحميل البيانات",
    },
    "hi": {
        "Home": "होम",
        "Bible": "बाइबल",
        "Ask": "पूछें",
        "Saved": "सहेजा गया",
        "Settings": "सेटिंग्स",
        "Profile": "प्रोफ़ाइल",
        "Notifications": "सूचनाएँ",
        "Appearance": "दिखावट",
        "Widgets": "विजेट",
        "Subscription": "सदस्यता",
        "About": "बारे में",
        "Name": "नाम",
        "Faith Level": "विश्वास का स्तर",
        "Life Seasons": "जीवन के चरण",
        "Heart Burdens": "हृदय के बोझ",
        "AI Memory": "AI मेमोरी",
        "Welcome": "स्वागत है",
        "Not set": "सेट नहीं है",
        "Empty": "खाली",
        "Digest only": "केवल सारांश",
        "Changes to your profile will refresh your feed.": "प्रोफ़ाइल में बदलाव आपकी फ़ीड को रिफ़्रेश कर देंगे।",
        "Prayer Times": "प्रार्थना समय",
        "Faith Boosts": "विश्वास की प्रेरणा",
        "Verses & prayers throughout your day": "पूरे दिन वचन और प्रार्थनाएँ",
        "Topics": "विषय",
        "Streak Reminders": "निरंतरता रिमाइंडर",
        "Plan Reminders": "योजना रिमाइंडर",
        "Language": "भाषा",
        "Soundscape": "साउंडस्केप",
        "Background": "पृष्ठभूमि",
        "Home Screen Widget": "होम स्क्रीन विजेट",
        "Lock Screen Widget": "लॉक स्क्रीन विजेट",
        "Widget Background": "विजेट पृष्ठभूमि",
        "Setup Guide": "सेटअप गाइड",
        "Upgrade to Pro": "Pro पर अपग्रेड करें",
        "Unlock all features & content": "सभी सुविधाएँ और सामग्री अनलॉक करें",
        "All features unlocked": "सभी सुविधाएँ अनलॉक हैं",
        "Manage": "प्रबंधित करें",
        "Restore Purchases": "खरीद बहाल करें",
        "PRO": "PRO",
        "Rate the App": "ऐप को रेट करें",
        "Privacy Policy": "गोपनीयता नीति",
        "Terms of Service": "सेवा की शर्तें",
        "Support": "सहायता",
        "Profile Picture": "प्रोफ़ाइल चित्र",
        "Choose from Library": "लाइब्रेरी से चुनें",
        "Remove Photo": "फ़ोटो हटाएँ",
        "Done": "हो गया",
        "Cancel": "रद्द करें",
        "Save": "सहेजें",
        "OK": "ठीक है",
        "Close": "बंद करें",
        "Continue": "जारी रखें",
        "Back": "वापस",
        "Next": "अगला",
        "Skip": "छोड़ें",
        "Delete": "हटाएँ",
        "Share": "साझा करें",
        "Copy": "कॉपी",
        "Edit": "संपादित करें",
        "System": "सिस्टम",
        "Follow device language": "डिवाइस की भाषा का पालन करें",
        "Languages": "भाषाएँ",
        "Search languages": "भाषाएँ खोजें",
        "Unable to Load Data": "डेटा लोड नहीं हो सका",
    },
    "id": {
        "Home": "Beranda",
        "Bible": "Alkitab",
        "Ask": "Tanya",
        "Saved": "Tersimpan",
        "Settings": "Pengaturan",
        "Profile": "Profil",
        "Notifications": "Notifikasi",
        "Appearance": "Tampilan",
        "Widgets": "Widget",
        "Subscription": "Langganan",
        "About": "Tentang",
        "Name": "Nama",
        "Faith Level": "Tingkat iman",
        "Life Seasons": "Musim kehidupan",
        "Heart Burdens": "Beban hati",
        "AI Memory": "Memori AI",
        "Welcome": "Selamat datang",
        "Not set": "Belum diatur",
        "Empty": "Kosong",
        "Digest only": "Ringkasan saja",
        "Changes to your profile will refresh your feed.": "Perubahan profil akan memperbarui feed-mu.",
        "Prayer Times": "Waktu doa",
        "Faith Boosts": "Penguat iman",
        "Verses & prayers throughout your day": "Ayat dan doa sepanjang harimu",
        "Topics": "Topik",
        "Streak Reminders": "Pengingat kelangsungan",
        "Plan Reminders": "Pengingat rencana",
        "Language": "Bahasa",
        "Soundscape": "Suasana suara",
        "Background": "Latar belakang",
        "Home Screen Widget": "Widget layar utama",
        "Lock Screen Widget": "Widget layar kunci",
        "Widget Background": "Latar widget",
        "Setup Guide": "Panduan pengaturan",
        "Upgrade to Pro": "Upgrade ke Pro",
        "Unlock all features & content": "Buka semua fitur & konten",
        "All features unlocked": "Semua fitur dibuka",
        "Manage": "Kelola",
        "Restore Purchases": "Pulihkan pembelian",
        "PRO": "PRO",
        "Rate the App": "Beri peringkat aplikasi",
        "Privacy Policy": "Kebijakan privasi",
        "Terms of Service": "Ketentuan layanan",
        "Support": "Dukungan",
        "Profile Picture": "Foto profil",
        "Choose from Library": "Pilih dari pustaka",
        "Remove Photo": "Hapus foto",
        "Done": "Selesai",
        "Cancel": "Batal",
        "Save": "Simpan",
        "OK": "OK",
        "Close": "Tutup",
        "Continue": "Lanjut",
        "Back": "Kembali",
        "Next": "Berikutnya",
        "Skip": "Lewati",
        "Delete": "Hapus",
        "Share": "Bagikan",
        "Copy": "Salin",
        "Edit": "Edit",
        "System": "Sistem",
        "Follow device language": "Ikuti bahasa perangkat",
        "Languages": "Bahasa",
        "Search languages": "Cari bahasa",
        "Unable to Load Data": "Tidak dapat memuat data",
    },
}


def build_catalog():
    strings = OrderedDict()
    for key, source, comment in STRINGS:
        entry = OrderedDict()
        if comment:
            entry["comment"] = comment
        entry["extractionState"] = "manual"
        localizations = OrderedDict()
        # Always include the English source so Xcode shows it as translated.
        localizations["en"] = {"stringUnit": {"state": "translated", "value": source}}
        for lang_code in sorted(TRANSLATIONS.keys()):
            mapping = TRANSLATIONS[lang_code]
            value = mapping.get(source)
            if value is not None:
                localizations[lang_code] = {
                    "stringUnit": {"state": "translated", "value": value}
                }
        entry["localizations"] = localizations
        strings[key] = entry

    return OrderedDict(
        [
            ("sourceLanguage", "en"),
            ("strings", strings),
            ("version", "1.0"),
        ]
    )


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.normpath(os.path.join(here, "..", "Resources"))
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "Localizable.xcstrings")
    catalog = build_catalog()
    with open(out_path, "w", encoding="utf-8") as f:
        # ensure_ascii=False so native characters write literally — Xcode
        # handles UTF-8 and the file stays human-readable.
        json.dump(catalog, f, ensure_ascii=False, indent=2)
    print(f"Wrote {out_path}")
    print(f"  {len(STRINGS)} source strings")
    print(f"  {len(TRANSLATIONS) + 1} languages (incl. source en)")


if __name__ == "__main__":
    main()
